### ISSUE TITLE
Typing Space

### ISSUE THREAD

**Issue by RogueMaster** [ranchordo/flipperzero-cli-bridge#1]
When holding underscore to type space it seems to crash or exit the app

**Comment by ranchordo** [comment]
This should be fixed now in release v1.1. The main problem was that a long press of the OK key was the signal to exit the app while keeping the inner CLI terminal connected and open (as opposed to sending Ctrl+C and exiting), but it also had the unintended side-effect of exiting the app when inputting a space using underscore (which I didn't know was possible). The fix was just to limit this behavior to the console output view.

**Comment by RogueMaster** [comment]
Thank you!
